name: Deploy to Azure Staging - backpack-ai-assistant-staging

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to ACR
        uses: docker/login-action@v2
        with:
          registry: backpackcrgstry.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image (staging)
        run: |
          docker build -t backpackcrgstry.azurecr.io/backpackapp-staging:latest .
          docker push backpackcrgstry.azurecr.io/backpackapp-staging:latest

      - name: Deploy to Azure Web App (staging)
        uses: azure/webapps-deploy@v2
        with:
          app-name: backpack-ai-assistant-staging
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_STAGING }}
          images: backpackcrgstry.azurecr.io/backpackapp-staging:latest
