# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - backpack-ai-assistant

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://backpackcrgstry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_975c4d1f0a604a8a8a558d6d080091a6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1fe87ee65566487caa71d36834e31ea3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: backpackcrgstry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_975c4d1f0a604a8a8a558d6d080091a6 }}/backpackapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'backpack-ai-assistant'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7deb60ce795a4b2a88ffa0f6ddbcaf87 }}
        images: 'backpackcrgstry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_975c4d1f0a604a8a8a558d6d080091a6 }}/backpackapp:${{ github.sha }}'